version: 2.1
setup: true

orbs:
  win: circleci/windows@2.4.0
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: dev
          mapping: |
            .. dash-modified true
          config-path: .circleci/workflows.yml
      - path-filtering/filter:
          base-revision: dev
          mapping: |
            packages/dash-core-components/.* dash-core-components-modified true
          config-path: packages/dash-core-components/.circleci/config.yml
      - path-filtering/filter:
          base-revision: dev
          mapping: |
            packages/dash-html-components/.* dash-html-components-modified true
          config-path: packages/dash-html-components/.circleci/config.yml
      - path-filtering/filter:
          base-revision: dev
          mapping: |
            packages/dash-table/.* dash-table-modified true
          config-path: packages/dash-table/.circleci/config.yml
